config/routes.rb
RoboMo::Application.routes.draw do
  resources :cc_users

  resources :ticket_links
  
  resources :tickets do
    collection do
      get 'perform_search'
      get 'autocomplete_tag_name'
      get 'autocomplete_ticket_sprint_tag'
      get 'autocomplete_tickets'
    end
    member do
      get 'delete'
      post 'change_state'
      post 'mark_as_duplicate'
      post 'mark_as_exclusive_with'
    end
    resources :posts
  end

  resources :tags do 
    member do
      delete :delete
    end
  end

  resources :assets
  match '/auth/google/callback' => 'authentication#create'

  match '/login' => 'authentication#new'
  match '/logout' => 'authentication#destroy'

  match '/toggle_notifications' => 'application#toggle_notifications'

  root :to => 'tickets#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  acts_as_taggable
  scope :state, proc {|state| state.present? ? where(:state => state) : nil}
  scope :with_creator, proc {|ignore| includes(:creator) }
  scope :scheduled, where("sprint_tag != '' AND state IN ('submitted','scheduled_for_estimation','estimated','in_progress')")
  paginates_per 50

  has_many :duplications
  has_many :duplicates, :through => :duplications
  has_many :inverse_duplications, :class_name => "Duplication", :foreign_key => "duplicate_id"
  has_many :inverse_duplicates, :through => :inverse_duplications, :source => :ticket
  def duplicate_tickets
    duplicates + inverse_duplicates
  end

  has_many :exclusive_withs
  has_many :exclusions, :through => :exclusive_withs
  has_many :inverse_exclusive_withs, :class_name => "ExclusiveWith", :foreign_key => "exclusion_id"
  has_many :inverse_exclusions, :through => :inverse_exclusive_withs, :source => :ticket

  has_many :ticket_links
  has_many :linked_ticket_ids, :through => :ticket_links, :source => :ticket
  has_many :ticket_ids, :through => :ticket_links, :source => :ticket
   
  def exclusive_with_tickets
    exclusions + inverse_exclusions
  end

  def linked_tickets
    Ticket.select("tl.id as ticket_link_id, tickets.id, tickets.summary ").
      joins("join ticket_links tl on tl.ticket_id = tickets.id or tl.linked_ticket_id = tickets.id").
      where("tl.ticket_id = :id or tl.linked_ticket_id = :id and tickets.id != :id", { :id => self.id }).
    delete_if { |t| t.id == self.id }.uniq
  end

  scope :sorted, proc {|sort_col, direction|
    sort_col = case sort_col
    when 'creator'
      "users.name"
    when 'importance'
      "coalesce(importance, 0)"
    when *(self.attribute_names)
      sort_col
    else
      sort_col = "case when updated_at > coalesce(last_post_at, '2001-01-01') then updated_at else last_post_at end"
    end
    direction = 'desc' unless direction == 'asc'

    if sort_col =~ /users/
      joins(:creator).order("#{sort_col} #{direction}")
    else
      order("#{sort_col} #{direction}")
    end
  }

  state_machine :state, :initial => :submitted do
    state :submitted
    state :postponed
    state :scheduled_for_estimation
    state :estimated
    state :in_progress
    state :released
    state :closed
    
    after_transition do |ticket, transition|
      StateChange.create!(:state => ticket.state, :ticket => ticket,
                          :user => ticket.last_modified_user, :changed_at => ticket.updated_at)
    end

    event :submitted do
      transition all - [:released, :submitted] => :submitted
    end
    
    event :postpone do
      transition all - [:released, :postponed] => :postponed
    end
    
    event :schedule_for_estimation do
      transition all - [:released, :scheduled_for_estimation] => :scheduled_for_estimation
    end

    event :mark_estimated do
      transition all - [:released, :estimated] => :estimated
    end

    event :begin_work do
      transition all - [:in_progress, :released] => :in_progress
    end

    event :release do
      transition all - [:released] => :released
    end
    
    event :close do
      transition all - [:closed] => :closed
    end
  end

  def self.states
    state_machines[:state].states.map(&:value)
  end

  has_many :posts
  has_many :assets, :dependent => :destroy
  has_many :state_changes, :dependent => :destroy
  has_many :cc_users, :dependent => :destroy
  accepts_nested_attributes_for :cc_users, :allow_destroy => true

  after_create :send_notification

  accepts_nested_attributes_for :assets, :allow_destroy => true

  belongs_to :creator, :class_name => 'User'
  belongs_to :last_modified_user, :class_name => 'User', :foreign_key => 'last_modified_by'

  validates_presence_of :summary, :description, :creator
  validates_inclusion_of :importance, :in => [nil,1,2,3,4]

  SEARCHABLE_FIELDS = :summary, :description

  def self.readiness_states
    [[1, "Idea:  This is an idea. Maybe good. Maybe bad. I am simply recording it for posterity."],
     [2, "Started: Maybe we have a sense of requirements of this. But someone has thought about it enough to start moving it forward."],
     [3, "Getting there: We've started talking about this and maybe even have an idea how to implement it. But may need designs or user testing or external approval to move forward."],
     [4, "Pretty close: There are some open questions, but we know enough to be able to estimate this and answer questions as we go."],
     [5, "Punch it, Chewy! This is well-understood, has designs (or doesn't need them) and is ready to be implemented now."]]
  end

  def readiness_word
    readiness ? Ticket.readiness_states[readiness - 1][1] : ""
  end

  def short_readiness_word
    readiness ? readiness_word.split(/[:!]/).first : ""
  end
 
  def self.importances
    [[1, "Nice to have"], [2, "Low importance"], [3, "Medium importance"], [4, "High importance"]]
  end

  def importance_word
    if importance
      Ticket.importances[importance - 1][1]
    else
      ""
    end
  end

  def short_importance_word
    importance_word.split(/:|importance/).first
  end

  def self.matching(query)
    conditions = SEARCHABLE_FIELDS.inject(nil) do |node, field|
      matcher = arel_table[field].matches("%#{query}%")
      node ? node.or(matcher) : matcher
    end

    where(conditions)
  end

  def last_update
    [updated_at, (last_post_at || 1.year.ago)].max
  end

  def thread_members
    ([self.creator] + self.posts.map(&:creator)).compact.uniq
  end

  def users_to_cc
    cc_users.map(&:user)
  end

  def unique_recipients
    (thread_members + users_to_cc + User.to_receive_all_emails).uniq
  end

  def send_notification
    mail = BugsMailer.new_ticket(self)
    mail.deliver if mail.to_addrs.present?
  end

  def set_time_to_first_reply
    unless self.time_to_first_reply_in_seconds
      seconds = Time.now.to_i - self.created_at.to_i
      self.update_attribute(:time_to_first_reply_in_seconds, seconds)
    end
  end

  def events
    (self.posts + self.state_changes).reject{|e| e.created_at.blank? }.sort_by{|e| e.created_at}
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_tags, :only => :index
  before_filter :assign_creator, :only => :create
  before_filter :find_ticket_and_assign_last_modified_by, :only => [:change_state, :update, :mark_as_duplicate, :mark_as_exclusive_with]
  respond_to :html

  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag' 

  has_scope :sorted, :using => [:col, :dir], :default => {:col => 'last_updated', :dir => 'desc'}
  has_scope :matching
  has_scope :page, :default => 1
  has_scope :state
  has_scope :scheduled
  has_scope :tagged_with, :type => :array 
  has_scope :created_at

  # TODO: this is a bit of a lame hack to always include the creator with
  # InheritedResources. I don't feel great about it.
  has_scope :with_creator, :default => 1

  new! do |format|
    @ticket.assets.build
  end

  edit! do |format|
    @ticket.assets.build
  end

  show! do |format|
    @post = @ticket.posts.build
    @post.assets.build
  end

  # no support for distinct values in autocomplete macro. jerks.
  def autocomplete_tickets
    query = "summary ilike ?"
    args = ["%#{params[:term]}%"]
    if params[:term] =~ /^\d+$/
      query += " or id = ?" 
      args << params[:term].to_i
    end
    render :json => (Ticket.select('id, summary').where(query, *args).map do |i| 
      {:label => "#{i.id} : #{i.summary}", :value => i.id}
    end)
  end

  def autocomplete_ticket_sprint_tag
    render :json => Ticket.select('distinct sprint_tag').where("sprint_tag ilike ?", "#{params[:term]}%").map(&:sprint_tag).map {|i| {:label => i, :value => i}}
  end

  def mark_as_duplicate
    ticket = Ticket.find params[:id]
    duplicate = Ticket.find params[:duplicate_id]
    ticket.duplicates << duplicate
    if ticket.save
      flash[:notice] = "Idea marked as a duplicate of #{duplicate.id} - #{duplicate.summary}"
    else 
      flash[:error] = "Something went wrong marking this idea as a duplicate."
    end
    redirect_to :action => :show
  end

  def mark_as_exclusive_with
    ticket = Ticket.find params[:id]
    other = Ticket.find params[:exclusive_with_id]
    ticket.exclusions << other
    if ticket.save
      flash[:notice] = "Idea marked as a exclusive with #{other.id} - #{other.summary}"
    else 
      flash[:error] = "Something went wrong marking this idea as a duplicate."
    end
    redirect_to :action => :show
  end

  def index
    super do |format|
      format.html { render :layout => !request.xhr? }
    end
  end

  def delete
    @ticket = Ticket.find_by_id(params[:id])
    @ticket.destroy
    flash[:notice] = "Idea #{@ticket.id} deleted"
    redirect_to :action => :index
  end

  def perform_search
    @search_term = params[:search][:term]
    @tickets = Ticket
    @tickets = @tickets.where("sprint_tag ilike :tag", {:tag => "%#{@search_term}%"}) if @search_term.present?
    @tickets = @tickets.where(:state => params[:search][:state]) if params[:search][:state].present?
    @tickets = @tickets.page(params[:page])
    params[:state] = 'search'
    render :action => "index"
  end

  def change_state
    @ticket.send(params[:transition])
    redirect_to ticket_path(@ticket)
  end

  def assign_creator
    params[:ticket][:creator_id] = current_user.id
    params[:ticket][:last_modified_by] = current_user.id
  end

  def find_ticket_and_assign_last_modified_by
    @ticket = Ticket.find_by_id(params[:id])
    @ticket.update_attributes(:last_modified_user => current_user)
    @ticket.save
  end
  
  def find_tags
    @tagged_tickets = apply_scopes(Ticket, params.reject{|k,v| k == 'page'})
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def tag_link_attributes(tag)
    tags = (params[:tagged_with] || []) + [tag.name]
    params.merge({:tagged_with => tags}).reject{|k,v| k.to_s == 'page'}
  end

  def showing_ticket_numbers
    page_start = (@tickets.current_page - 1) * Ticket.default_per_page
    "#{page_start + 1}-#{page_start + @tickets.size}"
  end

  def json_user_hash
    User.all.inject({}){|h, u| h[u.name] = u.id; h}.to_json
  end

  def not_on_cc_list?
    !(User.to_receive_all_emails + @ticket.users_to_cc).include?(current_user)
  end


  def turnaround_report
    avg = Ticket.where("last_post_at is not null").limit(25).average(:time_to_first_reply_in_seconds)
    if avg
      content_tag :p, :id => 'response-time' do
        "Average time to first response over the last 25 tickets: ".html_safe +
        content_tag(:strong, distance_of_time_in_words(avg))
      end
    end
  end

  def state_filter_link(state)
    link_text = "#{formatted_state(state)} (#{Ticket.state(state).matching(params[:matching]).count})"
    content_tag :li, :class => (params[:state] == state ? 'yah' : nil) do
      link_to(link_text, "/tickets?state=#{state}&matching=#{params[:matching]}")
    end
  end

  def tag_cloud_word
    (params[:state] || (params[:scheduled] ? 'scheduled' : 'popular')).titleize
  end

  def formatted_state(state)
    state.titleize.gsub(/Resolved/, "Resolved: ")
  end

  # ACTION LINKS
  def ticket_resolve_link(resolution)
    if @ticket.send("can_#{resolution}?") && ((@ticket.pending? && current_user == @ticket.creator) || current_user.admin?)
      button_to(resolution.to_s.titleize, ticket_state_change_url(resolution),
                :class => resolution)
    end
  end
  
  def ticket_submitted_link
    ticket_link_for("submitted", "Submitted", "submitted")
  end
  
  def ticket_postpone_link
    ticket_link_for("postpone", "Postpone", "postpone")
  end
  
  def ticket_begin_work_link
    ticket_link_for("begin_work", "Begin Work", "begin_work")
  end

  def ticket_release_link
    ticket_link_for("release", "Release", "release")
  end

  def ticket_close_link
    ticket_link_for("close", "Close", "close")
  end
  
  def ticket_mark_estimated_link
    ticket_link_for("mark_estimated", "Mark Estimated", "mark_estimated")
  end

  def ticket_schedule_for_estimation_link
    ticket_link_for("schedule_for_estimation", "Schedule For Estimation", "schedule_for_estimation")
  end


  def ticket_link_for(transition, link_text, link_class)
    if @ticket.send("can_#{transition}?") && current_user.admin?
      button_to(link_text, ticket_state_change_url(transition), :class => link_class)
    end
  end

  def ticket_state_change_url(action)
    "/tickets/#{@ticket.id}/change_state?transition=#{action}"
  end
end

app/views/tickets/_cc_form.haml
:javascript
  userHash = #{json_user_hash}

.ui-widget
  %label{:for => "cc-users"} Also CC:
  %input#cc-users{:placeholder => "Enter a name", :data => {'ticket-id' => @ticket.id}}

app/views/tickets/_cced_users.haml
- @ticket.unique_recipients.sort_by(&:name).each do |recipient|
  %li.recip{:id => "cc-user-#{recipient.id}"}
    = recipient.name
    - if (cc = @ticket.cc_users.detect{|c| c.user_id == recipient.id}) && (recipient == current_user || current_user.admin?)
      %a.remove-cc{:href => "#", :data => {'cc_user-id' => cc.id}} &times;

- unless @ticket.unique_recipients.include?(current_user)
  %li
    %button#cc-me{:data => {'ticket-id' => @ticket.id, 'user-id' => current_user.id}} Notify Me of Replies

app/views/tickets/_form.haml
= simple_form_for @ticket, :html => {:multipart => true} do |f|

  = f.input :summary, :label => 'Summary <span>Short summary of the idea.</span>'
  = f.input :description, :label => 'Description <span>More detailed summary of the idea.</span>'
  %div.input.string
    = f.label :tag_list, "Tags", :class => "string"
    = f.autocomplete_field :tag_list, autocomplete_tag_name_tickets_path, :"data-delimiter" => ', '

  - if current_user.admin?
    %div.input.string
      = f.label :sprint_tag, "Sprint", :class => "string"
      = f.autocomplete_field :sprint_tag, autocomplete_ticket_sprint_tag_tickets_path 
  #readiness
    %label.radio
      Readiness
      %span How actionable is this?
    %div.radio-options
      = f.collection_radio:readiness, Ticket.readiness_states, :first, :last

  #importance
    %label.radio
      Importance
      %span How important is this?
    %div.radio-options
      = f.collection_radio :importance, Ticket.importances, :first, :last

  #cc_new_users
    = f.label :cc_users, "CC Users", :class => "string"
    %ul#cced-users
      - User.to_receive_all_emails.sort_by(&:name).each do |recipient|
        %li.recip{:id => "cc-user-#{recipient.id}"}
          = recipient.name
      :javascript
        userHash = #{json_user_hash}
      %br
      %input.autocomplete{:placeholder => "Enter a name"}

  #assets
    %label.attachment
      Attach a File
    #files
      = f.fields_for :assets do |asset|
        = asset.file_field :content

  %p= f.button :submit, "Save Idea"

app/views/tickets/edit.haml
%h1 Edit Ticket
= render :partial => 'form'

app/views/tickets/index.haml
- is_home = params[:state].blank? && params[:scheduled].blank?
%h2.welcome
  Well hello there,
  %span #{current_user.name}!

%p#new-ticket
  = link_to "Submit a New Idea", new_ticket_path

- if params[:matching].present?
  %h3#search-stripe
    Search results for &ldquo;#{params[:matching]}&rdquo;
    %a{:href => "/"} (Remove search filter)

%nav#filters
  %ul.tabs
    %li{:class => (is_home ? 'yah' : nil)}= link_to("All (#{Ticket.matching(params[:matching]).count})", "/tickets?matching=#{params[:matching]}")
    
    = state_filter_link('submitted')
    = state_filter_link('postponed')
    = state_filter_link('scheduled_for_estimation')
    = state_filter_link('estimated')
    %li{:class => (params[:scheduled] == '1' ? 'yah' : nil)}
      = link_to("Scheduled (#{Ticket.scheduled.count})", '/tickets?scheduled=1')
    = state_filter_link('in_progress')
    = state_filter_link('released')
    = state_filter_link('closed')
    
    %li{:class => (params[:state] == 'search' ? 'yah' : nil)}= link_to("Search Tags", '/tickets?state=search')

- if params[:state] == 'search'
  = simple_form_for :tickets, :url => "/tickets/perform_search", :method => :get do
    = label_tag "search_term", "Search Tags:"
    = text_field :search, :term, :value => params[:search].try(:[], :term)
    = select :search, :state, Ticket.states, :include_blank => 'All', :selected => params[:search].try(:[], :state)
    = submit_tag "Search bugs"

- if params[:tagged_with].present?
  %h3 #{tag_cloud_word} ideas tagged with #{params[:tagged_with].to_sentence}
- else
  %h3 #{tag_cloud_word} ideas
#tag-cloud
  Filter by tags:
  - tag_cloud(@tagged_tickets.tag_counts_on(:tags), %w(tag-small tag-medium tag-big tag-biggest)) do |tag, css_class| 
    - unless params[:tagged_with].try(:member?, tag.name)
      = link_to tag.name, tag_link_attributes(tag), :class => css_class

- if @search_term
  %h3 Searching for bugs tagged with '#{@search_term}'

%p#display-count
  Showing #{showing_ticket_numbers} of
  %strong #{@tickets.total_count} #{params[:state].try(:titleize)}
  ideas
= paginate @tickets

%table
  %colgroup
    %col{:style => "width: 60%;"}
    %col
    %col
    %col
    %col
    %col
    %col
  %thead
    %tr
      %th{:data => {:sort => 'summary'}, :scope => "col"}
        Idea
        %span.icon
      %th{:data => {:sort => 'tags_list'}, :scope => "col"}
        Tags
        %span.icon
      %th{:data => {:sort => 'readiness'}, :scope => "col"}
        Readiness
        %span.icon
      %th{:data => {:sort => 'importance'}, :scope => "col"}
        Importance
        %span.icon
      %th{:data => {:sort => 'state'}, :scope => "col"}
        Status
        %span.icon
      %th{:data => {:sort => 'creator'}, :scope => "col"}
        Submitter
        %span.icon
      %th{:data => {:sort => 'sprint_tag'}, :scope => "col"}
        Scheduled For
        %span.icon
      %th{:data => {:sort => 'last_update'}, :scope => "col"}
        Updated
        %span.icon
      %th{:data => {:sort => 'created_at'}, :scope => "col"}
        Submitted
        %span.icon
      - if @search_term
        %th
          Tags
  %tbody
    - @tickets.each do |ticket|
      %tr
        %td.issue
          = link_to ticket.summary, ticket_path(ticket)
          - if ticket.posts_count > 0
            %em (#{pluralize(ticket.posts_count, "reply")})
        %td
          - ticket.tags.each do |t|
            = link_to t.name, params.merge({:tagged_with => [t.name]})
        %td.readiness{:alt => ticket.readiness_word}
          = ticket.short_readiness_word
        %td.importance{:alt => ticket.importance_word}
          = ticket.short_importance_word
        %td
          = formatted_state(ticket.state)
        %td
          = ticket.creator.name
        %td
          = ticket.sprint_tag || "Unscheduled"
        %td
          = smart_time(ticket.last_update)
          == by #{ ticket.last_modified_user.try(:name) }
        %td
          = smart_time(ticket.created_at)
          %br
        - if @search_term
          %td
            = ticket.sprint_tag

= paginate @tickets

app/views/tickets/new.haml
%h1 File a New Ticket
= render :partial => 'form'

app/views/tickets/show.haml
%section#ticket

  %h1
    %strong= @ticket.id
    #{@ticket.summary}
    %span (#{formatted_state(@ticket.state)})


  %ul.actions
    - if current_user.can_edit?(@ticket)
      %li= link_to("Edit Idea", edit_ticket_path(@ticket))
    %li= ticket_submitted_link
    %li= ticket_postpone_link
    %li= ticket_begin_work_link
    %li= ticket_release_link
    %li= ticket_close_link
    - if current_user.admin? 
      %li= ticket_schedule_for_estimation_link
      %li= ticket_mark_estimated_link
      %li= link_to("Delete Idea", delete_ticket_path(@ticket))
    %li= link_to("Mark As Duplicate", '#', :class => 'ticket-link-toggle', 'data-form' => 'mark_as_duplicate')
    %li= link_to("Mark As Exclusive With Another Idea", '#', :class => 'ticket-link-toggle', 'data-form' => 'mark_as_exclusive_with')
    %li= link_to("Mark As Part Of Another Idea", '#', :class => 'ticket-link-toggle', 'data-form' => 'ticket_links')
  .action-forms
    = form_tag :action => :mark_as_duplicate, :id => @ticket.id do |f|
      = autocomplete_field_tag '', '', autocomplete_tickets_tickets_path, :placeholder => "Search by idea id number or title", :class => 'ticket-linker'
      = hidden_field_tag :duplicate_id
      = submit_tag
    = form_tag :action => :mark_as_exclusive_with, :id => @ticket.id do |f|
      = autocomplete_field_tag '', '', autocomplete_tickets_tickets_path, :placeholder => "Search by idea id number or title", :class => 'ticket-linker'
      = hidden_field_tag :exclusive_with_id
      = submit_tag
    = form_tag :controller => :ticket_links, :action => :create, :id => @ticket.id do |f|
      = autocomplete_field_tag '', '', autocomplete_tickets_tickets_path, :placeholder => "Search by idea id number or title", :class => 'ticket-linker'
      = hidden_field_tag "ticket_link[linked_ticket_id]"
      = hidden_field_tag "ticket_link[ticket_id]", @ticket.id
      = submit_tag

  %p.meta-info
    Filed by
    %strong= @ticket.creator.name
    = smart_time(@ticket.created_at)

  %dl
    %dt Summary
    %dd= simple_format(auto_link(@ticket.summary))
  %dl
    %dt Description
    %dd= simple_format(auto_link(@ticket.description))
  - if @ticket.readiness
    %dl
      %dt Readiness
      %dd= @ticket.readiness_word
  - if @ticket.importance
    %dl
      %dt Importance
      %dd= @ticket.importance_word
  %dl
    %dt Tags
    %dd
      = @ticket.tag_list
      = button_tag "Edit", :class => 'edit-tags'

    = simple_form_for @ticket, :html => {:id=> 'inline-tag-edit'} do |f|
      %div.input.string
        = f.label :tag_list, "Tags", :class => "string"
        = f.autocomplete_field :tag_list, autocomplete_tag_name_tickets_path, :"data-delimiter" => ', '
        = f.button :submit, "Save Tags"

  %dl
    %dt Attachments
    %dd
      - if @ticket.assets.any?
        %ul.assets
          - @ticket.assets.each do |asset|
            %li= asset_link(asset, 'data-lightview-group' => "ticket-#{@ticket.id}")
  - if @ticket.duplicate_tickets.any? 
    %dl
      %dt Duplicates
      %dd
        %ul.duplicates
          - @ticket.duplicate_tickets.each do |dup|
            %li 
              = link_to "#{dup.id} - #{dup.summary}", ticket_path(dup)
  - if @ticket.exclusive_with_tickets.any? 
    %dl
      %dt Exclusive With
      %dd
        %ul.exclusive_with
          - @ticket.exclusive_with_tickets.each do |idea|
            %li 
              = link_to "#{idea.id} - #{idea.summary}", ticket_path(idea)
  - if @ticket.linked_tickets.any?
    %dl
      %dt Linked to Other Ideas
      %dd
        %ul.linked_tickets
        - @ticket.linked_tickets.each do |t|
          %li 
            = link_to "#{t.id} - #{t.summary}", ticket_path(t)
            (
            = link_to("remove", ticket_link_path(t['ticket_link_id']), :method => 'delete')
            )
%section#posts
  - if current_user.admin?
    #sprint-assignment
      = simple_form_for @ticket do
        Schedule to sprint:
        = text_field 'ticket', 'sprint_tag'
        = submit_tag "Assign to sprint", :id => 'submit-sprint-tag'

  - if @ticket.events.any?
    %h2 Responses
    #responses
      - @ticket.events.each do |event|
        - if event.instance_of?(Post)
          %dl.post
            %dt Response by #{event.creator.name} #{smart_time(event.created_at)}
            %dd= auto_link(simple_format(event.body))
            - if event.assets.any?
              %dd
                %ul.assets
                  - event.assets.each do |asset|
                    %li= asset_link(asset, 'data-lightview-group' => "post-#{event.id}", 'data-lightview-caption' => asset.caption)
        - elsif event.instance_of?(StateChange)
          %dl.state-change
            %dt
              Status Change
            %dd
              #{event.user.name} changed the status of this ticket to
              %span.state{:class => event.state}
                #{formatted_state(event.state)}
              #{smart_time(event.changed_at)}


  %h2#cced-header CC&rsquo;ed Users
  %ul#cced-users
    = render :partial => 'cced_users'

  = render :partial => 'cc_form'

  %h2 Post a Response
  = simple_form_for [@ticket, @post || @ticket.posts.build] do |f|
    = f.input :body, :label => "Your Response"

    #assets
      %label.attachment
        Attach File(s)
      #files
        = f.fields_for :assets do |asset|
          = asset.text_field :caption, :placeholder => "Attachment caption"
          = asset.file_field :content
 

    %p= f.button :submit, :value => 'Post Response'